Models/Ruta.cs
namespace WebAppCA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Ruta")]
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            Asignacion = new HashSet<Asignacion>();
        }

        [Key]
        public int id_ruta { get; set; }

        public int id_agencia { get; set; }

        [Column("Ruta")]
        [Required]
        [StringLength(20)]
        public string Ruta1 { get; set; }

        public virtual Agencia Agencia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion> Asignacion { get; set; }
    }
}

Controllers/EmpleadoController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAppCA.Models;
using WebAppCA.Entity;
namespace WebAppCA.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
       
        private static usp_ObtenerUsuario_Result SesionUsuario;
        public ActionResult Index()
        {
            if (Session["Usuario"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
          
        }
        

        public JsonResult Listar()
        {
            
            List<Empleado> lEmpleado = new List<Empleado>();
            using (Model db = new Model())
            {
                lEmpleado = db.Empleado.ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new { data = lEmpleado }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Tipo_cargo()
        {
            List<Cargo> cargos = new List<Cargo>();
            using (Model db = new Model())
            {
                cargos = db.Cargo.ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new { data = cargos }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Tipo_agencia()
        {
            List<Agencia> cargos = new List<Agencia>();
            using (Model db = new Model())
            {
                cargos = db.Agencia.ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new { data = cargos }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Tipo_concepto()
        {
            List<Concepto> concepto = new List<Concepto>();
            using (Model db = new Model())
            {
                concepto = db.Concepto.ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new {data=concepto }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Obtener(int idempleado)
        {
            Empleado oPersona = new Empleado();

            using (Model db = new Model())
            {
                
                oPersona = (from p in db.Empleado.Where(x => x.id_empleado == idempleado)
                            select p).FirstOrDefault();
                db.Configuration.LazyLoadingEnabled = false;
            }

            return Json(oPersona, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Guardar(Empleado oEmpleado)
        {
            bool respuesta = true;
            try
            {
                if (oEmpleado.id_empleado == 0)
                {
                    using (Model db = new Model())
                    {
                        db.Empleado.Add(oEmpleado);
                        db.SaveChanges();
                        db.Configuration.LazyLoadingEnabled = false;
                    }
                }
                else
                {
                    using (Model db = new Model())
                    {
                        Empleado tempempleado = (from p in db.Empleado
                                                where p.id_empleado == oEmpleado.id_empleado
                                                select p).FirstOrDefault();

                        tempempleado.Primer_nombre = oEmpleado.Primer_nombre;
                        tempempleado.Segundo_nombre = oEmpleado.Segundo_nombre;
                        tempempleado.Primer_apellido = oEmpleado.Primer_apellido;
                        tempempleado.Segundo_apellido = oEmpleado.Segundo_apellido;
                        tempempleado.Fecha_ingreso = oEmpleado.Fecha_ingreso;
                        tempempleado.id_cargo = oEmpleado.id_cargo;
                        tempempleado.id_agencia = oEmpleado.id_agencia;
                        tempempleado.Estado = oEmpleado.Estado;

                        db.SaveChanges();
                        db.Configuration.LazyLoadingEnabled = false;
                    }
                }
            }
            catch
            {
                respuesta = false;

            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult Eliminar(int idempleado)
        {
            bool respuesta = true;
            try
            {
                using (Model db = new Model())
                {
                    Empleado oEmpleado = new Empleado();
                    oEmpleado = (from p in db.Empleado.Where(x => x.id_empleado == idempleado)
                                select p).FirstOrDefault();
                    db.Empleado.Remove(oEmpleado);
                    db.SaveChanges();
                    db.Configuration.LazyLoadingEnabled = false;
                }
            }
            catch
            {
                respuesta = false;
            }
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Listar_E(int idempleado)
        {
            List<mostrar_empleado_id_Result> lEmpleado = new List<mostrar_empleado_id_Result>();
            using (Control_de_asistenciaEntities db = new Control_de_asistenciaEntities())
            {
                lEmpleado = db.mostrar_empleado_id(idempleado).ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new { data = lEmpleado }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Listar_EA()
        {
            if (Session["Usuario"] != null)
            {
                SesionUsuario = (usp_ObtenerUsuario_Result)Session["Usuario"];
            }
            else
            {
                SesionUsuario = new usp_ObtenerUsuario_Result();
            }
            List<SP_mostrar_empleados_Activos_Result> lEmpleado = new List<SP_mostrar_empleados_Activos_Result>();
            using (Control_de_asistenciaEntities db = new Control_de_asistenciaEntities())
            {
                lEmpleado = db.SP_mostrar_empleados_Activos(SesionUsuario.IdSucursal).ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new { data = lEmpleado }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult Obtener_empAsis(int idempleado)
        {
            List<SP_mostrar_empleado_asistencia_Result> lEmpleado = new List<SP_mostrar_empleado_asistencia_Result>();
            using (Control_de_asistenciaEntities db = new Control_de_asistenciaEntities())
            {
                lEmpleado = db.SP_mostrar_empleado_asistencia(idempleado).ToList();
                db.Configuration.LazyLoadingEnabled = false;

            }
            return Json(new {data=lEmpleado}, JsonRequestBehavior.AllowGet);
        }



    }
}

Controllers/rutaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppCA.Models;

namespace WebAppCA.Controllers
{
    public class rutaController : Controller
    {
        // GET: ruta
        public ActionResult Index()
        {
            return View();
        }



        public JsonResult Listar()
        {
            List<Ruta> lRuta = new List<Ruta>();
            using (Model db = new Model())
            {
                lRuta = db.Ruta.ToList();
                db.Configuration.LazyLoadingEnabled = false;
            }
            return Json(new { data = lRuta }, JsonRequestBehavior.AllowGet);
        }




        public JsonResult Obtener(int idruta)
        {
            Ruta oRuta = new Ruta();

            using (Model db = new Model())
            {

                oRuta = (from p in db.Ruta.Where(x => x.id_ruta == idruta)
                            select p).FirstOrDefault();
                db.Configuration.LazyLoadingEnabled = false;
            }

            return Json(oRuta, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Guardar(Ruta oRuta)
        {

            bool respuesta = true;
            try
            {
                if (oRuta.id_ruta== 0)
                {
                    using (Model db = new Model())
                    {
                        db.Ruta.Add(oRuta);
                        db.SaveChanges();
                        db.Configuration.LazyLoadingEnabled = false;
                    }
                }
                else
                {
                    using (Model db = new Model())
                    {
                        Ruta tempRuta = (from p in db.Ruta
                                               where p.id_ruta == oRuta.id_ruta
                                               select p).FirstOrDefault();

                        tempRuta.id_agencia = oRuta.id_agencia;
                        tempRuta.Ruta1 = oRuta.Ruta1;
                        
                        db.SaveChanges();
                        db.Configuration.LazyLoadingEnabled = false;
                    }
                }
            }
            catch (Exception E)
            {
                Console.WriteLine(E.Message);
                respuesta = false;

            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);


        }

        public JsonResult Eliminar(int idruta)
        {
            bool respuesta = true;
            try
            {
                using (Model db = new Model())
                {
                    Ruta oRuta= new Ruta();
                    oRuta = (from p in db.Ruta.Where(x => x.id_ruta == idruta)
                                select p).FirstOrDefault();
                    db.Ruta.Remove(oRuta);
                    db.SaveChanges();
                    db.Configuration.LazyLoadingEnabled = false;
                }
            }
            catch
            {
                respuesta = false;
            }
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/ruta/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                REGISTRO DE RUTAS
            </div>
            <br />

            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">AGENCIA</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <br />
                        <div class="modal-body">
                            <form action="/" method="post">
                                <div class="form-row">
                                    <input type="hidden" id="txtIdRuta" readonly />
                                    <div class="form-group col-md-6">
                                        <label for="nombre_ruta">RUTA</label>
                                        <input type="text" class="form-control" id="nombre_ruta" placeholder="Nombre Ruta">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="Papellido">Agencia</label>
                                        <select id="Agencia_" class="form-control">
                                            <option selected>Seleccione un agencia:</option>
                                        </select>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <br />
                        <br />
                        <br />
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                            <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
                        </div>
                    </div>
                </div>
            </div>



            <div class="card-body">
                <table id="tdruta" class="display responsive nowrap" style="width:100%">
                    <thead>
                        <tr>
                            <th>nombre_ruta</th>
                            <th>mantenimiento</th>
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>



</body>
</html>


@section    scripts{
    <script>
    $(document).ready(function () {

                $.ajax({
                    url: "@Url.Action("Tipo_agencia", "Empleado")",
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        var cargos = $('#Agencia_');
                        var datos = data.data;
                        $(datos).each(function (i, v) {
                            cargos.append('<option value="' + v.id_agencia + '">' + v.Nombre_agencia + '</option>');
                        });
                    },
                    error: function () {
                        console.log('err')
                    }

                });
    });

        var tabla_ruta;
    $(document).ready(function () {
        tabla_ruta = $('#tdruta').DataTable({
            "ajax": {
                "url":"@Url.Action("Listar","ruta")",
                "type": "GET",
                "contentType":"application/json; charset=utf-8",
                "dataType":"json"
            },
            "columns":[
                { "data": "Ruta1", "autoWidth": true },

                {
                    "data": "id_ruta", "autoWidth": true, "render": function (data) {
                        return "<button class='btn btn-primary btn-sm' type='button' onclick='abrirModal1(" + data + ")'><i class='fas fa-pen'></i></button>" +
                            "<button class='btn btn-danger btn-sm ml-2' type='button' onclick='Eliminar(" + data + ")'><i class='fa fa-trash'></i></button>"
                    },
                    "orderable": false,
                    "searchable": false,
                    "width": "150px",

                }],
                dom: 'Bfrtip',
                buttons: [
                    {
                        text: 'Agregar Nuevo',
                        attr: { class: 'btn btn-success btn-sm' },
                        action: function (e, dt, node, config) {
                            abrirModal1(0)
                        }
                    }
                 ],
                 "language": {
                     "url": "@Url.Content("~/Content/datatable/idioma/datatable.es-ES.json")"
                 }
        });
    });
        function abrirmodal($idruta) {
            alert($idruta);
        }

        function eliminar($idruta) {
            alert("Eliminar: " + $idruta);
        }

        $(document).ready(function () {
            $('#btnagregar').click(function (e) {
                abrirModal1(0);
            });
        });

        function abrirModal1($id_ruta) {

            $("#txtIdRuta").val($id_ruta);
        if ($id_ruta != 0) {

            jQuery.ajax({
                url: "@Url.Action("Obtener","ruta")" + "?idruta=" + $id_ruta,
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data != null) {
                       
                        $("#nombre_ruta").val(data["Ruta1"]);
                        $('#Agencia_ option[value= "' + data.id_agencia + '"]').prop('selected', true);
                        $('#exampleModalCenter').modal('show');
                    }
                }
            });
        }else {
            $("#nombre_agencia").val("");
            $('#Agencia_ option[selected]').prop('selected', true);
            $('#exampleModalCenter').modal('show');

            }

        }

        function Guardar() {
            var $data = {
                oRuta: {
                id_ruta: parseInt($("#txtIdRuta").val()),
                id_agencia: parseInt(document.getElementById('Agencia_').value),
                Ruta1: $("#nombre_ruta").val()
                }
            }

            jQuery.ajax({
                url: "@Url.Action("Guardar", "ruta")",
                type: "POST",
                data: JSON.stringify($data),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {


                    if (data.resultado) {
                        tabla_ruta.ajax.reload();
                        $("#exampleModalCenter").modal('hide');
                        $('body').removeClass('modal-open');
                        $('.modal-backdrop').remove();
                        alert("Datos Guardados Correctamente");
                        $("#nombre_ruta").val("");
                    } else {
                        alert("No se pudo guardar los cambios");
                       
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                }
            });

        }



    </script>>

    }